name: Robert Marcuccio Architects
favicon: null
layout_spectrum: 0.1563663526903838
typography_spectrum: 0.2633332668337971
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7068230838049203
  lightness: 0.7519122157245874
  saturation: 0.8000517815817147
  rhythmicContrast: 0.5018892821390182
purpose: []
