name: Robert Marcuccio Architects
favicon: null
layout_spectrum: 0.51084
typography_spectrum: 0.93506
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#181410'
    - '#655a41'
    - '#af9d7b'
    - '#963116'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
